@echo off
REM Hercules SFMS Production Build Script for Windows

echo ========================================
echo Hercules SFMS Production Build Script
echo ========================================
echo.

REM Check Node.js
where node >nul 2>nul
if %errorlevel% neq 0 (
    echo ERROR: Node.js is not installed. Please install Node.js 18+
    exit /b 1
)

echo Checking prerequisites...
node -v
npm -v
echo.

REM Clean install if --clean argument provided
if "%1"=="--clean" (
    echo Performing clean install...
    rmdir /s /q node_modules 2>nul
    rmdir /s /q dist 2>nul
    echo Cleaned node_modules and dist directories
    echo.
)

REM Install dependencies
echo Installing dependencies...
if exist package-lock.json (
    call npm ci --prefer-offline --no-audit
) else (
    call npm install
)
echo Dependencies installed
echo.

REM Check for .env file
if not exist .env (
    echo Creating default .env file...
    (
        echo # Hercules SFMS Environment Configuration
        echo # Generated by build script
        echo.
        echo # Server Configuration
        echo PORT=5000
        echo NODE_ENV=production
        echo.
        echo # Database Configuration
        echo # DATABASE_URL=postgresql://user:password@localhost:5432/hercules_sfms
        echo.
        echo # Security - REQUIRED for production
        echo JWT_SECRET=change-this-secret-key-in-production
        echo.
        echo # OAuth Configuration - Optional
        echo # VITE_GOOGLE_CLIENT_ID=your-google-client-id
    ) > .env
    echo Created .env file - Please update with production values!
    echo.
)

REM Type checking
echo Running type checks...
call npm run check 2>nul
if %errorlevel% neq 0 (
    echo Warning: Type checking had warnings - continuing build
)
echo.

REM Build application
echo Building application...
call npm run build
if %errorlevel% neq 0 (
    echo ERROR: Build failed
    exit /b 1
)
echo Application built successfully
echo.

echo ========================================
echo Build Complete!
echo.
echo Build Statistics:
echo   - Build time: %date% %time%
echo   - Output directory: dist
echo.
echo Next Steps:
echo   1. Review the .env file configuration
echo   2. Set up PostgreSQL database (optional)
echo   3. Run 'npm start' to start the server
echo   4. Access at http://localhost:5000
echo.
echo For more information, see README.md
echo ========================================