#!/bin/bash

# Hercules SFMS Production Build Script
# This script prepares the application for production deployment

set -e  # Exit on error

echo "🚀 Hercules SFMS Production Build Script"
echo "========================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check Node.js version
echo ""
echo "📋 Checking prerequisites..."
if ! command -v node &> /dev/null; then
    print_error "Node.js is not installed. Please install Node.js 18+ first."
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    print_error "Node.js version 18+ is required. Current version: $(node -v)"
    exit 1
fi
print_status "Node.js $(node -v) detected"

# Check for npm
if ! command -v npm &> /dev/null; then
    print_error "npm is not installed"
    exit 1
fi
print_status "npm $(npm -v) detected"

# Parse arguments
CLEAN_INSTALL=false
SKIP_TESTS=true
ENV_FILE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --clean)
            CLEAN_INSTALL=true
            shift
            ;;
        --with-tests)
            SKIP_TESTS=false
            shift
            ;;
        --env)
            ENV_FILE="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: ./build.sh [--clean] [--with-tests] [--env <file>]"
            exit 1
            ;;
    esac
done

# Clean install if requested
if [ "$CLEAN_INSTALL" = true ]; then
    echo ""
    echo "🧹 Performing clean install..."
    rm -rf node_modules dist
    print_status "Cleaned node_modules and dist directories"
fi

# Install dependencies
echo ""
echo "📦 Installing dependencies..."
if [ -f "package-lock.json" ]; then
    npm ci --prefer-offline --no-audit
    print_status "Dependencies installed from lock file"
else
    npm install
    print_status "Dependencies installed"
fi

# Check for environment file
echo ""
echo "🔧 Checking environment configuration..."
if [ -n "$ENV_FILE" ] && [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" .env
    print_status "Environment file copied from $ENV_FILE"
elif [ ! -f ".env" ]; then
    print_warning "No .env file found. Creating from template..."
    cat > .env << EOF
# Hercules SFMS Environment Configuration
# Generated by build script

# Server Configuration
PORT=5000
NODE_ENV=production

# Database Configuration
# Uncomment and configure for PostgreSQL
# DATABASE_URL=postgresql://user:password@localhost:5432/hercules_sfms

# Security (REQUIRED for production)
JWT_SECRET=$(openssl rand -base64 32)

# OAuth Configuration (Optional)
# VITE_GOOGLE_CLIENT_ID=your-google-client-id
EOF
    print_status "Created .env file with default configuration"
    print_warning "Please review and update .env file with production values"
fi

# Type checking
echo ""
echo "🔍 Running type checks..."
if npm run check 2>/dev/null; then
    print_status "Type checking passed"
else
    print_warning "Type checking had warnings (continuing build)"
fi

# Build the application
echo ""
echo "🔨 Building application..."
npm run build
print_status "Application built successfully"

# Run tests if not skipped
if [ "$SKIP_TESTS" = false ]; then
    echo ""
    echo "🧪 Running tests..."
    if npm test 2>/dev/null; then
        print_status "Tests passed"
    else
        print_warning "Some tests failed (continuing)"
    fi
fi

# Create production info file
echo ""
echo "📝 Creating build info..."
cat > dist/build-info.json << EOF
{
  "version": "$(node -p "require('./package.json').version")",
  "buildDate": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "nodeVersion": "$(node -v)",
  "npmVersion": "$(npm -v)",
  "environment": "production"
}
EOF
print_status "Build info created"

# Calculate build size
BUILD_SIZE=$(du -sh dist | cut -f1)

# Final output
echo ""
echo "========================================"
echo -e "${GREEN}✨ Build Complete!${NC}"
echo ""
echo "📊 Build Statistics:"
echo "   • Build size: $BUILD_SIZE"
echo "   • Node version: $(node -v)"
echo "   • Build time: $(date)"
echo ""
echo "🚀 Next Steps:"
echo "   1. Review the .env file configuration"
echo "   2. Set up your PostgreSQL database (optional)"
echo "   3. Run 'npm start' to start the production server"
echo "   4. Access the application at http://localhost:5000"
echo ""
echo "📚 For more information, see README.md"
echo "========================================"